### ISSUE TITLE
Ubuntu Packaging Guide: Add explanation about SRU

### ISSUE THREAD

**Issue by rkratky** [canonical/open-documentation-academy#102]
## Context

The Ubuntu Packaging Guide (UPG) is undergoing a rewrite that's intended to bring it up-to-date with current processes and state of the art. A part of that effort includes streamlining various topics and making them more user-friendly and compliant with Diataxis framework.

One of these topics is **Stable Release Update (SRU)**. Given that SRU is a complex process and its docs are lengthy, the UPG will only have a brief **explanation** of what it is and then links to detailed docs elsewhere.

## Task

Add an explanation article (following Diataxis guidelines about 'explanations') about SRU to the UPG at [stable-release-updates.rst](https://github.com/canonical/ubuntu-packaging-guide/blob/2.0-preview/docs/explanation/stable-release-updates.rst).

## Reference

Use the following resources to learn more about the process to be described as well as the Diataxis framework and the existing UPG content.

- Ubuntu wiki: [StableReleaseUpdates](https://wiki.ubuntu.com/StableReleaseUpdates)
- Old UPG: [Security and Stable Release Updates](https://ubuntu-packaging-guide.readthedocs.io/en/latest/ubuntu-packaging-guide/security-and-stable-release-updates.html)
- Diataxis: [Explanation](https://diataxis.fr/explanation/)
- ReadTheDocs: [Ubuntu Packaging Guide](https://canonical-ubuntu-packaging-guide.readthedocs-hosted.com/en/latest/)
- GitHub: [ubuntu-packaging-guide](https://github.com/canonical/ubuntu-packaging-guide)

**Comment by activus-d** [comment]
@rkratky I would like to work on this

**Comment by rkratky** [comment]
Hi @activus-d. Great -- thanks for picking this up. I have assigned you to the issue. Let me know if you have any questions.

**Comment by activus-d** [comment]
@rkratky I have made a pull request to solve this issue, and it is now available for your review.

**Comment by rkratky** [comment]
Referencing: https://github.com/canonical/ubuntu-packaging-guide/pull/69

**Comment by rkratky** [comment]
This has been merged into the Packaging Guide. Thanks, @activus-d!
