### ISSUE TITLE
Netplan: Add `netplan try` to Netplan tutorial

### ISSUE THREAD

**Issue by rkratky** [canonical/open-documentation-academy#103]
## Context

While the Netplan docs already have a tutorial, it's missing information about the useful `netplan try` command. Further reasoning: it complements the `netplan apply` command, and it's been a well-received feature by the community.

## Task

Showcase the `netplan try` command in the [Applying new Netplan configuration](https://netplan.readthedocs.io/en/latest/netplan-tutorial/#applying-new-netplan-configuration) section of the Netplan tutorial.

## Reference

- Diataxis: [Tutorial](https://diataxis.fr/tutorial/)
- ReadTheDocs: [Netplan documentation](https://netplan.readthedocs.io/)
- GitHub: [netplan](https://github.com/canonical/netplan/tree/main/doc)

**Comment by davidekete** [comment]
Hi @rkratky , I'd like to work on this

**Comment by rkratky** [comment]
Great, thanks for your interest, @davidekete. I assigned the item to you.

**Comment by davidekete** [comment]
Hi @rkratky, I'm done with this. I'm currently trying to open a PR to the netplan repo but I'm having an issue with the check list. 
Particularly these two:
- [ ] Runs `make check` successfully.
- [ ] Retains 100% code coverage (`make check-coverage`).

Running `make check` throws the error below:
```
Sphinx error:
Builder name check not registered or available through entry point
```
Running `make check-coverage` throws a similar error:
```
Sphinx error:
Builder name check-coverage not registered or available through entry point
```

**Comment by rkratky** [comment]
Those commands are meant to be run from the root directory of the repo, not from the `doc/` directory. The error messages are telling you that the `Makefile` (in the `doc/` directiry) does not have `check` and `check-coverage` targets defined. These targets are defined in the `Makefile` that's in the repo's main directory.
```
user@machine:netplan/doc$ cd ..
user@machine:netplan$ make check
user@machine:netplan$ make check-coverage
```

**Comment by davidekete** [comment]
Hi, thanks for the correction. I had tried that initially but got a weird error. However, after your comment, I took a look and got past the error. After that, I faced a lot of other errors related to missing dependencies. However, I still can't get it to run after installing them. Here's what I'm getting currently.
```
meson.build:82:0: ERROR: Tried to use not-found external program as test exe
```
Can you help?

**Comment by davidekete** [comment]
> Hi, thanks for the correction. I had tried that initially but got a weird error. However, after your comment, I took a look and got past the error. After that, I faced a lot of other errors related to missing dependencies. However, I still can't get it to run after installing them. Here's what I'm getting currently.
> 
> ```
> meson.build:82:0: ERROR: Tried to use not-found external program as test exe
> ```
> 
> Can you help?

Hi @rkratky, Just following up on this

**Comment by rkratky** [comment]
Apologies for the silence. I should be able to look into it tomorrow.

Could you please push the branch to your fork (no need to create a PR just yet), so that I could pull it and work with exactly the same as what you have?

**Comment by davidekete** [comment]
Hi @rkratky, no problem. I have pushed the changes to my fork. Here's [the link](https://github.com/davidekete/netplan/tree/Add-netplan-try-to-Netplan-tutorial).

**Comment by rkratky** [comment]
> > ```
> > meson.build:82:0: ERROR: Tried to use not-found external program as test exe
> > ```

Line 82 in `meson.build` says `test('codestyle'`, so you need to install the `codestyle` tool to be able to run the specified test. You can find it in the `pycodestyle` package on Ubuntu.

That said, I've now run the tests, and I see there are some errors in the code, but nothing that would be caused by the changes you introduced. So, you're good to go.

Please, submit a PR against the Netplan repo.

............

One suggestion: In step 3 of the procedure you modified, you added a note:

"Skip this step if you confirmed the changes using `netplan try`."

I think that could be confusing because while `netplan try` requires the user to confirm the changes to make them permanent, 'confirm' can also mean just "verify that the changes are OK". i'd suggest saying explicitly something like:

"Skip this step if you made the changes permanent using `netplan try`."

.............

One correction:

"Applies the new configuration temporarily (120 seconds by default) and waits for confirmation (within the specified time) to make them permanent."

->

"Applies the new configuration temporarily (120 seconds by default) and waits for confirmation (within the specified time) to make **_it_** permanent."

**Comment by davidekete** [comment]
Hi @rkratky, thank you for your help, the suggestion, and the correction. I have applied them and opened [the PR](https://github.com/canonical/netplan/pull/494). I wanted to know if we could add setting up a local development environment guide for the Netplan docs. It took me a while to do it, and I imagine others might have encountered the same issues. What do you think?

**Comment by rkratky** [comment]
> Hi @rkratky, thank you for your help, the suggestion, and the correction. I have applied them and opened [the PR](https://github.com/canonical/netplan/pull/494).

:+1:

> I wanted to know if we could add setting up a local development environment guide for the Netplan docs. It took me a while to do it, and I imagine others might have encountered the same issues. What do you think?

I suppose this would be an extension of https://canonical-netplan.readthedocs-hosted.com/en/latest/contribute-docs/

- You're right that there could be more. I think there's enough about the actual docs, but it could include a short section on how to do what's needed in order to open a PR (i.e. satisfy the conditions for actual Netplan development).
- And it could better placed -- now it's rather hidden among all the other howtos.

**Comment by davidekete** [comment]
Yes, an extension of https://canonical-netplan.readthedocs-hosted.com/en/latest/contribute-docs/, which I agree should be better placed (I'm just finding out it exists). I'm glad you agree. Can you open another issue and assign it to me?

**Comment by rkratky** [comment]
I created the issue: https://github.com/canonical/open-documentation-academy/issues/122. But you need to comment under the issue before the system let's me assign it to you.

**Comment by davidekete** [comment]
> I created the issue: #122. But you need to comment under the issue before the system let's me assign it to you.

Thank you. I just commented. Any update on my open PR: https://github.com/canonical/netplan/pull/494. The spell checker failed but it wasn't due to any changes I made.

**Comment by rkratky** [comment]
Completed. Thank you, @davidekete!
