### ISSUE TITLE
Ubuntu Packaging Guide: Fix repo README

### ISSUE THREAD

**Issue by rkratky** [canonical/open-documentation-academy#105]
# Context

The Ubuntu Packaging Guide (UPG) repository has a standard README file that could use some improvements. This is  a very simple and straightforward task suitable even for complete beginners.

## Task

Fix the following two issues:

- The mark-up used for the `https://github.com/pradyunsg/furo>` link (in the first section of the README) is broken. See the screenshot for reference: ![image](https://github.com/canonical/open-documentation-academy/assets/6623103/e3d56276-efab-4f70-b854-4780a713952c)

- The README is missing a link to the actual (built) docs on ReadTheDocs (https://canonical-ubuntu-packaging-guide.readthedocs-hosted.com/). This link should be in the first section of README. See, for example, https://github.com/canonical/netplan for inspiration.

## Reference

- ReadTheDocs: [Ubuntu Packaging Guide](https://canonical-ubuntu-packaging-guide.readthedocs-hosted.com/en/latest/)
- GitHub: [ubuntu-packaging-guide](https://github.com/canonical/ubuntu-packaging-guide)

**Comment by dviererbe** [comment]
This issue got resolved by 
- https://github.com/canonical/ubuntu-packaging-guide/pull/55
- https://github.com/canonical/ubuntu-packaging-guide/pull/56
- https://github.com/canonical/ubuntu-packaging-guide/pull/57
- https://github.com/canonical/ubuntu-packaging-guide/pull/59
- https://github.com/canonical/ubuntu-packaging-guide/pull/60

Thanks for your contributions ❤️

**Comment by chris-bateman** [comment]
Could this issue be closed then or is more work required?

**Comment by rkratky** [comment]
> Could this issue be closed then or is more work required?

Just an oversight. Thank you!
