### ISSUE TITLE
Netplan: Create snippet files for single-sourcing repetitive instructions

### ISSUE THREAD

**Issue by rkratky** [canonical/open-documentation-academy#107]
## Context

Three of the how-to guides for Netplan feature very similar scenarios, and all of them include certain instructions that are completely the same. In order to simplify maintenance and to ensure consistency, the instructions should be single-sourced from common source. This requires creating a separate file (or files) with these instruction snippets and including them in the how-tos. These are the how-tos:

- [How to configure a VM host with a single network interface](https://netplan.readthedocs.io/en/latest/single-nic-vm-host/)
- [How to configure a VM host with a single network interface and three VLANs](https://netplan.readthedocs.io/en/latest/single-nic-vm-host-with-vlans/)
- [How to configure a VM host with bonded network interfaces and three VLANs](https://netplan.readthedocs.io/en/latest/multi-nic-vm-host-with-bonds-and-vlans/)

## Task

1. Identify substantial parts of the how-tos that are exactly the same (always at least a section -- not just individual instruction steps or other small parts) and create a separate (`.md`) files from them. The content needs to be repeated in at least two of the how-tos (if in three, even better).

2. Remove the respective parts from the how-tos and substitute them for include statements that will render the snippets in those places. See [Embed & Include Content](https://mystmd.org/guide/embed) for instructions on how to do that in Markdown using the MyST extension.

## Reference

- Diataxis: [Tutorial](https://diataxis.fr/tutorial/)
- ReadTheDocs: [Netplan documentation](https://netplan.readthedocs.io/)
- GitHub: [netplan](https://github.com/canonical/netplan/tree/main/doc)

**Comment by nielsenjared** [comment]
Hey @rkratky! I'm interested in this issue. Is there a timeline for completion?

**Comment by rkratky** [comment]
Nice @nielsenjared. No real deadline 😌 Of course, it wouldn't be good to block the issue without really intending to work on it. Should I assign it to you?

**Comment by nielsenjared** [comment]
I'll take it!

**Comment by rkratky** [comment]
Done and dusted :) Thank you, @nielsenjared!
