### ISSUE TITLE
Multipass: Improve documentation for the "multipass mount" command

### ISSUE THREAD

**Issue by giuliazanchi** [canonical/open-documentation-academy#112]
## Context

[Multipass docs](https://multipass.run/docs) are in reasonably good shape, but there are (as always) little things that could be improved to offer a better user experience. 

Multipass docs are maintained in and published from the Ubuntu Discourse forum. To suggest changes in a Discourse-hosted docs page, scroll all the way down to the bottom of the page and open the page to which the "Help improve this document in the forum" link points. On the Discourse page, scroll to the bottom of the article (if there are comments, then the bottom of the article is just where the comments start, i.e. not at the very bottom of the page) and click "Edit". (You need an account on Ubuntu Discourse.) See also: [Contribute to Multipass docs](https://multipass.run/docs/contribute-to-multipass-docs).

## Task

The reference page for the [`multipass mount`](https://multipass.run/docs/mount-command) command needs to be improved, as it currently only lists the output of `multipass help mount`. 

Make sure to cover both classic and native mounts, which are briefly described here: [Mount](https://multipass.run/docs/mount).

For this task, you may take inspiration from other pages in the [Command-Line Interface](https://multipass.run/docs/multipass-cli-client) section or apply a different approach, as long as you don't revolutionise the template (otherwise, we'd have to update all other pages as well for consistency!) and include the output of `multipass help mount` at the bottom of the page. Please note that CLI reference pages are not yet auto-generated from the code but maintained manually. 

## Useful links

Before you get started, make sure to review the main concepts of the [Diátaxis](https://diataxis.fr/) documentation framework and also check the [Canonical Documentation Style Guide](https://docs.ubuntu.com/styleguide/en/).

If you are new to the Canonical Open Documentation Academy, you may also want to review our [Getting Started](https://discourse.ubuntu.com/t/getting-started/42769) topic on the Ubuntu Discourse forum.

**Comment by davidekete** [comment]
Hi @giuliazanchi, I'd like to work on this

**Comment by giuliazanchi** [comment]
Hi @davidekete , this is just a friendly reminder to check if you still intend to give this a go :) Thanks!

**Comment by davidekete** [comment]
> Hi @davidekete , this is just a friendly reminder to check if you still intend to give this a go :) Thanks!

Hi @giuliazanchi. I have been occupied these last few weeks, I'll work on this in the coming week. Thanks for reminder.

**Comment by giuliazanchi** [comment]
> > Hi @davidekete , this is just a friendly reminder to check if you still intend to give this a go :) Thanks!
> 
> Hi @giuliazanchi. I have been occupied these last few weeks, I'll work on this in the coming week. Thanks for reminder.

Brilliant, thanks! No need to feel rushed, I was just checking :)

**Comment by davidekete** [comment]
> Command-Line Interface

Hi @giuliazanchi, I don't think I have access to edit. Can you create an export of the page on the repo?

**Comment by davidekete** [comment]
Hi @giuliazanchi, I created a PR here https://github.com/canonical/open-documentation-academy/pull/134. I tried to add you as a reviewer, but for some reason, I'm unable to.

**Comment by giuliazanchi** [comment]
Thanks, @davidekete ! I'll share my feedback shortly :)
