### ISSUE TITLE
Launchpad: group articles of the Explanation section into proper subsections

### ISSUE THREAD

**Issue by jugmac00** [canonical/open-documentation-academy#115]
Documentation: https://documentation.ubuntu.com/launchpad/en/latest/explanation/
GitHub repo: https://github.com/canonical/launchpad-manual
Contribution guide: https://documentation.ubuntu.com/launchpad/en/latest/contribute-to-our-docs/

The explanation section contains a vast list of links to articles giving valuable background information to developers who want to contribute to Launchpad.

The length of the list makes the page ( https://documentation.ubuntu.com/launchpad/en/latest/explanation/ ) very inaccessible.

Ideally, we want to group the items into coherent subtopics, and also offer a quick introduction to these subtopics, similar what has been done for https://documentation.ubuntu.com/launchpad/en/latest/how-to/

This issue involves two parts:
- create coherent subtopics, which might need involvement from the Launchpad team (e.g. @jugmac00)
- once the articles has been grouped into these subtopics, both on the index page https://documentation.ubuntu.com/launchpad/en/latest/explanation/ and on the menu to the left this subgroups need to be created

The second part of the issue has been done before by @nbarbarick in https://github.com/canonical/launchpad-manual/pull/56 - have a look at that PR to get an idea what needs to be done.

**Comment by nbarbarick** [comment]
Hello, can I be assigned this issue? 

I could likely suggest subtopics and consult on introductory text before the end of next week.

**Comment by jugmac00** [comment]
That is fantastic news! @nbarbarick, thanks for picking this up!

@degville would you kindly assign @nbarbarick? Thank you!

**Comment by nbarbarick** [comment]
So, @jugmac00, would you prefer that I post questions or suggestions on the grouping of subtopics in this thread or in some other forum?

**Comment by jugmac00** [comment]
Thanks for asking. Indeed I think it makes sense to have that discussion on the Launchpad bug tracker at https://github.com/canonical/launchpad-manual/issues/80 - so the technical authors who maintain this generic bug tracker do not get flooded with notifications.

Also, all Launchpad engineers are subscribed to the above mentioned board, so you should get better turnaround when I am not available.

**Comment by nbarbarick** [comment]
Hi @jugmac00, I see my pull request was merged and closed, and just wanted to note it here. Thank you! 👍

**Comment by jugmac00** [comment]
Thanks a lot @nbarbarick! I cannot emphasize how much of value you generated for us! This contribution is really amazing!
