### ISSUE TITLE
Multipass: Improve the guide "How to set up a graphical interface"

### ISSUE THREAD

**Issue by giuliazanchi** [canonical/open-documentation-academy#128]
## Context

[Multipass docs](https://multipass.run/docs) are in reasonably good shape, but there are (as always) little things that could be improved to offer a better user experience. 

Multipass docs are maintained in and published from the Ubuntu Discourse forum. To suggest changes in a Discourse-hosted docs page, scroll all the way down to the bottom of the page and open the page to which the "Help improve this document in the forum" link points. On the Discourse page, scroll to the bottom of the article (if there are comments, then the bottom of the article is just where the comments start, i.e. not at the very bottom of the page) and click "Edit". (You need an account on Ubuntu Discourse.) See also: [Contribute to Multipass docs](https://multipass.run/docs/contribute-to-multipass-docs).

## Task

The how-to guide [How to set up a graphical interface](https://multipass.run/docs/set-up-a-graphical-interface) could be improved, for example by making the instructions to discover the IP address of the instance more intuitive and effective (see [issue #3641 on the Multipass repo](https://github.com/canonical/multipass/issues/3641)). 
While testing the instructions in this guide, look out for any additional improvements that could be made to the overall UX and flow.

## Useful links

Before you get started, make sure to review the main concepts of the [Diátaxis](https://diataxis.fr/) documentation framework and also check the [Canonical Documentation Style Guide](https://docs.ubuntu.com/styleguide/en/).

If you are new to the Canonical Open Documentation Academy, you may also want to review our [Getting Started](https://discourse.ubuntu.com/t/getting-started/42769) topic on the Ubuntu Discourse forum.

**Comment by DanRoscigno** [comment]
Thanks @giuliazanchi , please assign me.

**Comment by giuliazanchi** [comment]
Thanks for your lightning-speed contribution, @DanRoscigno ! I'll copy over these changes to Discourse and mention you there as well.
