### ISSUE TITLE
Landscape: "PPA" term entry

### ISSUE THREAD

**Issue by YanisaHS** [canonical/open-documentation-academy#13]
Write an explanation of **PPAs** and how they relate to Landscape. Your entry shouldn’t simply describe what a PPA is; the goal is to explain how PPAs *relate to Landscape*. For example, PPAs are used in the Landscape [quickstart installation](https://ubuntu.com/landscape/docs/quickstart-deployment) and [client installation](https://ubuntu.com/landscape/docs/install-landscape-client).

You should provide the entry as a Markdown file and put it in this file path: `landscape/explanation/glossary/ppa.md`. If any directories are missing, add them so your file path matches the one provided.

## Prerequisites

A general understanding of how Landscape works and experience using and installing Landscape. 

However, you don’t need any prior experience if you’re willing to explore the [Landscape Docs](https://ubuntu.com/landscape/docs) and spend time learning about Landscape.

See also: [Diátaxis - Explanation](https://diataxis.fr/explanation/) and [Contribute to our documentation](https://ubuntu.com/landscape/docs/contribute-to-the-landscape-documentation).

**Comment by CBID2** [comment]
Can I be assigned to this @YanisaHS?

**Comment by YanisaHS** [comment]
@CBID2 Absolutely!!! :smiley: 

I've [left a comment on another issue](https://github.com/canonical/open-documentation-academy/issues/14) with some more details. Just linking it here as well in case you find it useful.

Let us know if you have any more questions! Otherwise, I'm looking forward to seeing your PR. (We'll also help you through the review process - your PR doesn't have to be perfect!) 😃

**Comment by CBID2** [comment]
Hi @YanisaHS! :) Sorry for the radio silence. I'm still sifting through LandScape's documentation, so it's going to take me a while to create my Pull Request.

**Comment by YanisaHS** [comment]
@CBID2 Sounds good. Thanks for the update! :smiley:
