### ISSUE TITLE
Anbox Cloud: Improve contributing guide

### ISSUE THREAD

**Issue by keirthana** [canonical/open-documentation-academy#131]
Context

The Anbox Cloud documentation includes a [contributing guide](https://documentation.ubuntu.com/anbox-cloud/en/latest/contribute/landing/). However, it is not intuitive from the TOC. It also lacks information about the [checks](https://github.com/canonical/anbox-cloud-docs/actions) that need to be passed when creating a PR to the Anbox Cloud documentation repository.

Task

- Rename the [Project and Community](https://documentation.ubuntu.com/anbox-cloud/en/latest/contribute/landing/#) TOC heading to _Contribute_. (Retain the style guide as a sub topic)
- Add prerequisites required to contribute to Anbox Cloud documentation (GitHub account, signing the CLA)
- Add information about what checks are in place for PRs created against the [repository](https://github.com/canonical/anbox-cloud-docs)

Reference
Diataxis: [How-to guides](https://diataxis.fr/how-to-guides/)
A good example of a contributing guide: [LXD contributing guide](https://documentation.ubuntu.com/lxd/en/latest/contributing/#contribute-to-the-documentation)

**Comment by faithuniterh** [comment]
I would like to work on this

**Comment by keirthana** [comment]
> I would like to work on this

Thannk you @faithuniterh, please have a look at the resources linked and let me know if you need any additional information.

**Comment by keirthana** [comment]
@faithuniterh I see that you have created a PR for "Rename the [Project and Community](https://documentation.ubuntu.com/anbox-cloud/en/latest/contribute/landing/#) TOC heading to Contribute. (Retain the style guide as a sub topic)". 

Are you working on the remaining points of this issue on the same PR?

**Comment by keirthana** [comment]
@faithuniterh Will you be able to continue working on the remaining parts of the issue?

**Comment by faithuniterh** [comment]
@keirthana My intention is to work under the same PR, unless stated otherwise
Yes I will be able to continue working on the remaining parts.

**Comment by keirthana** [comment]
> @keirthana My intention is to work under the same PR, unless stated otherwise Yes I will be able to continue working on the remaining parts.

Thank you, I will review once all the changes are in.

**Comment by keirthana** [comment]
@faithuniterh Please let me know if you are unable to work on this any more. I can release the issue into the open pool of issues so that someone else can pick it up.

**Comment by keirthana** [comment]
Releasing this back into the pool of issues.

**Comment by PitifulPete** [comment]
Hi @keirthana, I would love to pick this up

**Comment by keirthana** [comment]
> Hi @keirthana, I would love to pick this up

Go for it, @PitifulPete. Let me know if you need any help with it.

**Comment by PitifulPete** [comment]
@keirthana: https://github.com/canonical/anbox-cloud-docs/pull/151

**Comment by keirthana** [comment]
> @keirthana: [canonical/anbox-cloud-docs#151](https://github.com/canonical/anbox-cloud-docs/pull/151)

@PitifulPete Thank you so much for your help on this. I have left some minor suggestions on the PR. Once they are addressed, I should be able to merge it.

**Comment by keirthana** [comment]
Thank you for your work on this @PitifulPete!
