### ISSUE TITLE
Anbox Cloud: Fix broken tables

### ISSUE THREAD

**Issue by keirthana** [canonical/open-documentation-academy#132]
Context

The [release notes](https://documentation.ubuntu.com/anbox-cloud/en/latest/reference/release-notes/release-notes/) page of Anbox Cloud documentation has some broken tables at the end.

Task

- Fix the broken tables for 2019 and 2018 headings
- Make the "older releases" section collapsible

Anbox Cloud documentation repository: https://github.com/canonical/anbox-cloud-docs

**Comment by ElAsJay** [comment]
Hi @keirthana, I'd like to work on this. 

- Expected due date: 31st, Aug, 2024

**Comment by keirthana** [comment]
> Hi @keirthana, I'd like to work on this.
> 
>     * Expected due date: 31st, Aug, 2024

Thank you @ElAsJay, I have assigned this issue to you. Let me know if you need any information.

**Comment by ElAsJay** [comment]
I created the pull request. Please kindly review it and let me know if I need to fix anything.

**Comment by keirthana** [comment]
@ElAsJay I have left a comment on the PR for you. Let me know if you need more help with it.

**Comment by keirthana** [comment]
@ElAsJay Will you be able to continue working on this issue? Please let me know of anything if you need help with.
We would prefer to keep issues moving, so if you are unable to continue work on this, please let me know.

**Comment by keirthana** [comment]
@ElAsJay This issue was fixed as part of a release update. So I am closing this issue.
