### ISSUE TITLE
Anbox Cloud: Update landing pages

### ISSUE THREAD

**Issue by keirthana** [canonical/open-documentation-academy#133]
Context

Anbox Cloud documentation has landing pages for each of the Diataxis sections (Tutorials, How-to guides, Explanation and Reference). The sub-pages for each of these sections are added to the landing pages in a meaningful way with a one-line description. Recently, the documentation has undergone some changes but the landing pages are not updated.

Task
Review and update the [How-to](https://documentation.ubuntu.com/anbox-cloud/en/latest/howto/landing), [explanation](https://documentation.ubuntu.com/anbox-cloud/en/latest/explanation/landing/) and [reference](https://documentation.ubuntu.com/anbox-cloud/en/latest/reference/landing/) landing pages.

Link to documentation repository: https://github.com/canonical/anbox-cloud-docs

**Comment by slpcxb** [comment]
Hi, can I take this task?

**Comment by keirthana** [comment]
> Hi, can I take this task?

@slpcxb Of course, I have assigned it to you. Let me know if you need any help.

**Comment by keirthana** [comment]
Thank you @slpcxb, the changes are now merged.
