### ISSUE TITLE
Landscape: "SSL certificate" term entry

### ISSUE THREAD

**Issue by YanisaHS** [canonical/open-documentation-academy#14]
Write an explanation of **SSL certificates** and how they relate to Landscape. Your entry shouldn’t simply describe what SSL certs are; the goal is to explain how SSL certs *relate to Landscape*. For example, you are guided to install a SSL cert in the [Landscape quickstart installation](https://ubuntu.com/landscape/docs/quickstart-deployment).

You should provide the entry as a Markdown file and put it in this file path: `landscape/explanation/glossary/ssl-cert.md`. If any directories are missing, add them so your file path matches the one provided.

## Prerequisites

A general understanding of how Landscape works and experience using and installing Landscape. 

However, you don’t need any prior experience if you’re willing to explore the [Landscape Docs](https://ubuntu.com/landscape/docs) and spend time learning about Landscape.

See also: [Diátaxis - Explanation](https://diataxis.fr/explanation/) and [Contribute to our documentation](https://ubuntu.com/landscape/docs/contribute-to-the-landscape-documentation).

**Comment by Owslla** [comment]
Hello @YanisaHS, I'm interested in working on this task. If I'm reading this right, the format would be a glossary entry as part of the larger Landscape documentation?  Do you happen to have a sample or similar writing I might look at?  I'm specially, interested in the general tone, expected audience, and any formatting you are expecting. Thank you.

**Comment by YanisaHS** [comment]
Hey @Owslla! Thanks for your interest! I'll assign you the issue :smile: 

Yes, you read it right - I essentially want a glossary entry as part of the larger [Landscape documentation](https://ubuntu.com/landscape/docs), but it should be written around how SSL certs relate to Landscape, **NOT** simply what an SSL certificate is in general.

**Sample**: I haven't made the section where this will ultimately be published yet, so unfortunately I don't have a direct example, but this write up on [access groups in Landscape](https://ubuntu.com/landscape/docs/reference-terms#heading--access-groups) would be a good comparison. The section for [Administrators](https://ubuntu.com/landscape/docs/reference-terms#heading--administrators) would also be a good example. As you'll see, the focus for both terms are still on Landscape, and "access group" and "administrators" aren't just defined in a general sense. The Juju docs also have a similar collection of terms, here's an example: [Controller](https://juju.is/docs/juju/controller).

**Tone**: If you look through the Landscape Docs, you'll get an understanding of the basic tone. I'd consider the tone to be slightly conversational (contractions are okay!), but still direct, and not quite as narrative or friendly as a blog/content article might be. 

**Expected audience**: Our audience has a very wide range of skills. You should do your best to write in a style that is still approachable for beginner audiences, although it's okay to assume some general knowledge on Landscape.

**Formatting**: You should bold the first occurrence of the word "SSL certificate" (similar to the examples I linked above). Othere than that, there isn't any specific formatting expected.

Let us know if you have any more questions! Otherwise, I'm looking forward to seeing your PR. (We'll also help you through the review process - your PR doesn't have to be perfect!) :smiley:

**Comment by Owslla** [comment]
I have submitted the pull request #37

**Comment by YanisaHS** [comment]
@Owslla Thanks for your wonderful contribution!!! :partying_face: :tada: It's live here: https://ubuntu.com/landscape/docs/explanation-ssl-certificates

If you have any feedback to share about your experience with Canonical's Open Docs Academy, please feel free to share it. Hope to work with you again! :smiley_cat:

**Comment by Owslla** [comment]
@YanisaHS Your welcome. I enjoyed the process and appreciated your clear instructions and feedback.  I look forward to the next one.
