### ISSUE TITLE
LXD: Clarify the difference between `show` and `info`

### ISSUE THREAD

**Issue by ru-fu** [canonical/open-documentation-academy#15]
Documentation: https://documentation.ubuntu.com/lxd/en/latest/
GitHub repo: https://github.com/canonical/lxd
Contribution guide: https://documentation.ubuntu.com/lxd/en/latest/contributing/

---
Most LXD commands have both a `show` and an `info` subcommand (for example, [`lxc network show`](https://documentation.ubuntu.com/lxd/en/latest/reference/manpages/lxc/network/show/#lxc-network-show-md) and [`lxc network info`](https://documentation.ubuntu.com/lxd/en/latest/reference/manpages/lxc/network/info/#lxc-network-info-md)).

`show` shows the configuration of the entity and which other resources are referencing it.
`info` gets state information, such as usage metrics.

This difference should be clarified in a general section in the docs.
In addition, we should make sure that we are listing both `show` and `info` for the commands where both are supported.

**Comment by pgfaller** [comment]
Hi @ru-fu - for my next trick I'd like to take this on. It looks quite substantial, so I expect it will take a couple of weeks

**Comment by ru-fu** [comment]
Thanks @pgfaller ! I've assigned the issue to you.

Just get in touch if you have any questions. :)

**Comment by pgfaller** [comment]
Hi @ru-fu - I've put up a draft pull request - please have a look and comment. I hope I'm on the right track.

**Comment by pgfaller** [comment]
Thanks for your feedback, @ru-fu. I've made the changes you suggested (all
good suggestions), so please take a look. I went through all the places I
could find 'lxc list/info/show ...' occurrences, and didn't find any gaps.
I'll check again hen time permits.

**Comment by pgfaller** [comment]
@ru-fu Anything more I must do on this?

**Comment by ru-fu** [comment]
@pgfaller Thanks for the reminder! I wanted to check in with you to hear if you needed any help with the PR. :)

The reason the PR hasn't been merged yet is that some of your commits are missing the sign-off line. Also, all commits are about the same feature, so they should ideally be reduced to one commit.
[This answer](https://stackoverflow.com/a/5201642) has instructions for how to do this - but you should add a `-s` to the `git commit` command to sign the commit.

Let me know if you run into any trouble with that!

**Comment by ru-fu** [comment]
@pgfaller Hmm, not sure what happened there ...
If you look at the commit list of the PR (https://github.com/canonical/lxd/pull/13327/commits), there are now 9 commits. The one you want (https://github.com/canonical/lxd/pull/13327/commits/76f060d7163d7bb7a652662418850672e9a5180c) looks good and is signed off correctly, but I honestly have no idea where the others come from ...

Git can be really tricky, and it's hard to debug it remotely, unfortunately. :worried: 
Since your changes are to only two files, the easiest might just be to create a new branch and copy the changes over. And then open a new PR. Of course, that's not the most elegant solution (I'm sure there is one, but I can't think of any myself now :wink: ), but it should work.

If it doesn't work, let me know, then I'll see if I can do something to fix this.

**Comment by pgfaller** [comment]
@ru-fu I was thinking along the same lines - new PR is https://github.com/canonical/lxd/pull/13404

**Comment by ru-fu** [comment]
And it's published! :tada: 
https://documentation.ubuntu.com/lxd/en/latest/explanation/lxc_show_info/

Thanks a lot @pgfaller !
