### ISSUE TITLE
LXD: Add `lxc config device override` to the docs

### ISSUE THREAD

**Issue by ru-fu** [canonical/open-documentation-academy#16]
Documentation: https://documentation.ubuntu.com/lxd/en/latest/
GitHub repo: https://github.com/canonical/lxd
Contribution guide: https://documentation.ubuntu.com/lxd/en/latest/contributing/

---
The LXD documentation has a section about [configuring devices](https://documentation.ubuntu.com/lxd/en/latest/howto/instances_configure/#configure-devices) that explains how you can add a device and configure it. 
However, there is a special command to modify devices that are inherited from a [profile](https://documentation.ubuntu.com/lxd/en/latest/profiles/), namely [`lxc config device override`](https://documentation.ubuntu.com/lxd/en/latest/reference/manpages/lxc/config/device/override/#lxc-config-device-override-md).

We should add this command and some explanation on when it should be used to the "Configure devices" section (for CLI, API, and UI).

**Comment by MCoooo** [comment]
Hi @ru-fu , I'm interested taking the plunge with this one. However I would need novice guidance :).

**Comment by ru-fu** [comment]
Hi @MCoooo - great, thanks for your interest!

And sure, please ask about anything that's unclear.

The first step for this task would be to read up a bit on LXD, mainly about devices and profiles, and try to determine where you think this new information should go.
And then the next step would be to jump right in and do the required changes! If you're familiar with Git, you can do them directly on the LXD repo, otherwise we can find an easier way to get them in. :)

**Comment by MCoooo** [comment]
Hi @ru-fu - apologies for the lack of activity.

I've finally done some reading and playing with LXD and the doc system.

I could not find any associated behaviour in API or UI so my initial proposed changes are a little under whelming. I've attempted to go the Git route. Would you like to review my fork before I try a PR or should I just send.

Fork is here: https://github.com/MCoooo/lxd/tree/oda-issue16-dev-override

As much feedback as you wish is welcome :)

**Comment by ru-fu** [comment]
Oh, and you're totally correct about the API and UI - in the API, you use the same command for overriding the options as for setting them, so there is no update needed. And the UI guides you through what you need to do, so no need to document this.

**Comment by MCoooo** [comment]
Thank you for the feedback, much appreciated.

I have made another attempt via https://github.com/canonical/lxd/pull/13418

Let me know if further polishing needed :)

**Comment by ru-fu** [comment]
Thanks a lot, @MCoooo ! This has now been merged. :)
