### ISSUE TITLE
LXD: Document the preseed file format for `lxc init`

### ISSUE THREAD

**Issue by ru-fu** [canonical/open-documentation-academy#17]
Documentation: https://documentation.ubuntu.com/lxd/en/latest/
GitHub repo: https://github.com/canonical/lxd
Contribution guide: https://documentation.ubuntu.com/lxd/en/latest/contributing/

---
You can initialize LXD through a preseed file - see [Non-interactive configuration](https://documentation.ubuntu.com/lxd/en/latest/howto/initialize/#non-interactive-configuration).
This section also contains an example for a preseed file. However, this is only an example and does not contain all available fields. For example, it is missing the fields for clusters (some of these are included in [How to form a cluster](https://documentation.ubuntu.com/lxd/en/latest/howto/cluster_form/)).

The top-level struct is:
```
config: {}
	networks: []
	storage_pools: []
	profiles: []
	projects: []
	cluster:
	  server_name: ""
	  enabled: false
	  member_config: []
	  cluster_address: ""
	  cluster_certificate: ""
	  server_address: ""
	  cluster_password: ""
	  cluster_certificate_path: ""
	  cluster_token: ""
```

We should add a reference page that contains the full file format, and link to it from the initialization and clustering how-tos.
This requires some research/checking the code and testing.

**Comment by activus-d** [comment]
Hi @ru-fu! I would like to work on this issue.

**Comment by ru-fu** [comment]
Thanks @activus-d ! I've assigned the issue to you now.

Let me know if anything is unclear!

**Comment by ru-fu** [comment]
Thanks a lot @activus-d ! This has now been merged. :)

https://documentation.ubuntu.com/lxd/en/latest/reference/preseed_yaml_fields/
