### ISSUE TITLE
ubuntu-image: Make root README.md better for pkg.go.dev.

### ISSUE THREAD

**Issue by rkratky** [canonical/open-documentation-academy#21]
## Background

The pkg.go.dev site auto-imports info from a (participating) repo’s main README. The page generated for the ubuntu-image project is at [pkg.go.dev/github.com/canonical/ubuntu-image](https://pkg.go.dev/github.com/canonical/ubuntu-image).

## Task

In order for the 'landing page' on pkg.go.dev to provide useful info, the repo's README should be modified. The README needs to serve two purposes:

* Introduction to the project and meta-info about the repo (i.e. what you would expect from a typical repo README).
* Getting started instructions and links to relevant info for visitors of the page on pkg.go.dev.

Additionally, the README should feature a 'Snap Store card' linking to the [ubuntu-image page on the Snap Store](https://snapcraft.io/ubuntu-image) (see the *Create embeddable card* button on that page).

**Comment by rkratky** [comment]
Nice. Let me know if you need anything.

**Comment by rkratky** [comment]
One note: Another contributor has already started on a related ubuntu-image issue (#20), and they submitted a PR that touches the README file. In order to avoid any dup[lication of efforts and/or potential conflicts, I suggest you either have a look at the pending [PR](https://github.com/canonical/ubuntu-image/pull/194), or wait until it's merged.

**Comment by activus-d** [comment]
Thank you for the update @rkratky. I will work on another issue pending the merging of the other PR.

**Comment by rkratky** [comment]
@activus-d The PR that could potentially cause conflicts has been merged, so if you'd like to pick this issue up, now's the time :-)

**Comment by activus-d** [comment]
Thank you for the update @rkratky. I will start working on the issue.

**Comment by rkratky** [comment]
> Thank you for the update @rkratky. I will start working on the issue.

Cool. Don't hesitate to let me know if you need anything!

**Comment by activus-d** [comment]
@rkratky I want to start working on the issue now but I don't think I have the permission to assign issues to myself as I can't find the `assign yourself` button.


![image](https://github.com/canonical/open-documentation-academy/assets/98895460/f7b1525d-6e74-4d99-b98d-9fe6ca05a187)

**Comment by rkratky** [comment]
Oh, I didn't realize that. Let me do that.

**Comment by activus-d** [comment]
@rkratky Is the information contained [here](https://discourse.ubuntu.com/t/using-ubuntu-image/35216) suitable for getting started?

**Comment by activus-d** [comment]
@rkratky I've made a pull request to solve this issue and it's now ready for your review.

**Comment by rkratky** [comment]
Fixed by https://github.com/canonical/ubuntu-image/pull/210
