### ISSUE TITLE
Public cloud: clean up custom_wordlist.txt and make corresponding updates to other files

### ISSUE THREAD

**Issue by k-dimple** [canonical/open-documentation-academy#26]
GitHub repo: https://github.com/canonical/ubuntu-cloud-docs

.custom_wordlist.txt contains a list of allowed words (that have to be ignored during spellcheck). It includes duplicates and words that use the wrong case. Duplicates have to be removed and a single consistent spelling (including case) has to be used throughout the documentation set. 

For this, update the .custom_wordlist.txt file, run `make spelling` for each project within the repo (as shown below) and then make appropriate corrections in other files.
```
PROJECT=all-clouds make spelling
PROJECT=aws make spelling
PROJECT=azure make spelling
PROJECT=google make spelling
PROJECT=ibm make spelling
PROJECT=oracle make spelling
PROJECT=oci make spelling
```
For words related to canonical products, follow the [branding guideline](https://docs.ubuntu.com/styleguide/en#branding).

**Comment by 0x923831bf343f** [comment]
Hello, wanted to ask if I can be assigned to this? @k-dimple

**Comment by k-dimple** [comment]
Sure @maxsaint-festin, I have just assigned it to you! Let me know if face any problems.

**Comment by k-dimple** [comment]
Sure @krzysiekwie, the custom_wordlist is over 200 words long and it might actually be a good idea to share the work! So maybe @maxsaint-festin could focus on the first 100 words and @krzysiekwie, you could take up the remaining. 

@maxsaint-festin hope that sounds okay?

**Comment by krzysiekwie** [comment]
@k-dimple 
Two more questions at the risk of getting micromanaged ;) 
Do you mind if I sort the `.custom_wordlist.txt` alphabetically (to match the sort in .wordlist.txt) at least temporarily? 

How exactly do you want duplicates handled? 
Some of the words (off the top of my head "Diátaxis" and "Juju") are duplicates from .worlist.txt - should actually get removed from `.custom_wordlist.txt`? 
The only full duplicate (same case) in the custom_wordlist seems to be `TMX`. 

But you have e.g. [Adapter and adapter](https://github.com/canonical/ubuntu-cloud-docs/blob/41ffed64d25153476f9b7a21541b2b456508500b/aws/aws-explanation/canonical-offerings.rst?plain=1#L63) 
in:
```
* `Elastic Fabric Adapter`_ - which allows high-performance applications to directly access the network adapter and get reliable transport with low-latency.
```
(both uses legitimate as in https://aws.amazon.com/hpc/efa/) 

Based on requirements.txt it looks like you're using pyspelling (I'm more into cspell). Before I start experimenting with it, am I right thinking that:

- `adapter` (one entry - all lowercase) in the custom_words allows all possible capitalizations,
- `Adapter` (one entry - specific capitalization) requires this capitalization, flags all others as incorrect,
- and having both `Adapter` and `adapter` allows these two capitalizations but not `adApter` etc?

**Comment by k-dimple** [comment]
Hey @krzysiekwie,
> Do you mind if I sort the .custom_wordlist.txt alphabetically (to match the sort in .wordlist.txt) at least temporarily?
No, please feel free

> Some of the words (off the top of my head "Diátaxis" and "Juju") are duplicates from .worlist.txt - should actually get removed from .custom_wordlist.txt?
Yes, please remove them from .custom_wordlist.txt

``adapter``  (one entry - all lowercase) allows both ``Adapter`` and ``adapter`` but not ``adApter`` etc. So we can just stick to ``adapter``

**Comment by krzysiekwie** [comment]
@k-dimple I didn't want to overcomplicate it with re-sorting just the second half of the file or sorting the whole list but waiting for @maxsaint-festin to try and figure out who does what. The [PR](https://github.com/canonical/ubuntu-cloud-docs/pull/212) makes the spellcheck clean for all the projects. 

One thing left to do here is getting rid of different case duplicates with the main .wordlist.txt: 'ebs', 'eks', 'kubernetes', 'lts', 'ubuntu', 'vm'. I'll be taking a break here for 2 weeks from next weekend, so could either fix it whole or leave it for @maxsaint-festin and possibly pick it up in May.

**Comment by k-dimple** [comment]
Since this is now merged, I'll close the issue here. Thanks again!
