### ISSUE TITLE
Public cloud: Left-align grids

### ISSUE THREAD

**Issue by k-dimple** [canonical/open-documentation-academy#27]
GitHub repo: https://github.com/canonical/ubuntu-cloud-docs

In the main index.rst file of each project within the repo, grids are used to create diataxis sections as seen in the screenshot below. The grids are not aligned with the rest of the text (e.g. 'How-to guides' is not directly below 'In this documentation'), and we would like that to be aligned. Check if the 'padding' field of ['grid options'](https://sphinx-design.readthedocs.io/en/latest/grids.html#grid-options) can be used to achieve the required alignment.

![image](https://github.com/canonical/open-documentation-academy/assets/123362247/2bbcf0d7-a5bf-4440-b3d0-dbbcfcebf50f)

The appropriate changes have to be included and tested in each index.rst where the grids are used.

**Comment by keith-taylor** [comment]
I'm not sure you get the grids to render? Even in Preview mode the I can just see the markdown for the grids? 
![Screenshot 2024-03-09 at 16 14 13](https://github.com/canonical/open-documentation-academy/assets/60480970/6f76652f-2627-4d1f-8ef0-f030398774cc)

**Comment by k-dimple** [comment]
Hi Keith, sorry, I should have worded that better. 'The **text within the** grids are not aligned with the rest of the text and we would like that to be aligned.' Like you mentioned, the grids themselves (i.e. their borders) are not rendered, but that is fine.

**Comment by keith-taylor** [comment]
I've added 0 padding to the Azure index.rst file but without being able to see it render I'm not sure if this works or not?

See here: https://github.com/keith-taylor/ubuntu-cloud-docs/compare/main...keith-taylor-patch-1

**Comment by k-dimple** [comment]
It should work, but you can test it and see the effect locally on your machine using [these instructions](https://canonical-azure.readthedocs-hosted.com/en/latest/azure-how-to/contribute-to-these-docs/#new-content).
For testing different clouds, you'll have to change the commands and use the correct cloud name in the PROJECT variable, as mentioned in the [repo's readme](https://github.com/canonical/ubuntu-cloud-docs/blob/main/readme.rst).

**Comment by keith-taylor** [comment]
So I've tried to run `make file` (I had to install `make` first) but I'm getting an error: 
```
❯ make build
. .sphinx/venv/bin/activate; sphinx-build -M build "." "_build" -c . -d .sphinx/.doctrees 
/bin/sh: 1: sphinx-build: not found
make: *** [Makefile:109: build] Error 127
```
I tried creating the `venv` directory using `python3 -m venv venv ` in the `.sphinx` directory to see if it was an issue with installing `venv` or creating that folder. This hasn't fixed anything. 

I've had a read thought the `Makefile`, `Contribute to these docs` and `readme.rst` files. Nothing obvious pops out.

I'm not sure how best to proceed?

**Comment by keith-taylor** [comment]
OK, I tried this on my mac — worked first time. PR submitted.

**Comment by k-dimple** [comment]
Hi Keith .. sorry about the delay in responding. Since 'build' is not defined in the Makefile, it resulted in that error. If you just want to build, without watching & serving the documentation you can use `make html`. In fact you can run just `make` to see all the options available.

I am glad it worked on your mac! I hope it works on the earlier machine too. Meanwhile I have merged your PR :)

**Comment by keith-taylor** [comment]
No worries

> Hi Keith .. sorry about the delay in responding. Since 'build' is not defined in the Makefile, it resulted in that error. If you just want to build, without watching & serving the documentation you can use `make html`. In fact you can run just `make` to see all the options available.
> 
> I am glad it worked on your mac! I hope it works on the earlier machine too. Meanwhile I have merged your PR :)

**No worries at all! Thanks for all your help.**
