### ISSUE TITLE
Public cloud (Sphinx): Content of a selected tab should remain visible even if it is re-selected.

### ISSUE THREAD

**Issue by k-dimple** [canonical/open-documentation-academy#28]
GitHub repo: https://github.com/canonical/ubuntu-cloud-docs

The repo uses tabbed content in multiple places, for instance [here](https://canonical-aws.readthedocs-hosted.com/en/latest/aws-how-to/instances/find-ubuntu-images/#finding-images-with-ssm). Visibility of a tab's content is toggled whenever the tab is clicked twice consecutively. Check if this behaviour can be modified to keep the content of a selected tab always visible.

Apply and test the changes to all pages with tabbed content.

**Comment by activus-d** [comment]
@k-dimple I would like to work on this issue.

**Comment by k-dimple** [comment]
Sure @activus-d, thanks! I have assigned it to you.
