### ISSUE TITLE
Public cloud: Change a text based table to a list-based table

### ISSUE THREAD

**Issue by k-dimple** [canonical/open-documentation-academy#29]
GitHub repo: https://github.com/canonical/ubuntu-cloud-docs

An [explanation page](https://github.com/canonical/ubuntu-cloud-docs/blob/main/google/google-explanation/gce-image-retention-policy.rst) in the google project contains a table written in a code block. It should be converted into a more standard .rst based list-table (for instance like the one used [here](https://github.com/canonical/ubuntu-cloud-docs/blob/main/google/google-how-to/gce/upgrade-in-place-from-lts-to-pro.rst)).

**Comment by gerryRcom** [comment]
Hi k-dimple, I would be happy to work on this issue, should get it done over the weekend if that works? Thanks!

**Comment by k-dimple** [comment]
Hi @gerryRcom , thank you so much for offer! There's just one little problem though. Another contributor has already submitted a PR for this issue yesterday (on the main source repo). Since he didn't put a comment here, I couldn't add him as an assignee and now I'll be closing this issue soon. So could you consider taking up one of the other issues from the list? We'll be happy to help with all of them.
