### ISSUE TITLE
Public cloud: Update readme with links to per project contribution guidelines

### ISSUE THREAD

**Issue by k-dimple** [canonical/open-documentation-academy#40]
GitHub repo: https://github.com/canonical/ubuntu-cloud-docs

Update the repo's readme.rst file to include links to each sub-project's contribution guidelines. There are 7 sub-projects, each with its own 'Contribute to these docs' page. So put links to them, e.g. [this](https://canonical-aws.readthedocs-hosted.com/en/latest/aws-how-to/contribute-to-these-docs/) is the link to the AWS project.

**Comment by activus-d** [comment]
@k-dimple I would like to work on this issue.

**Comment by k-dimple** [comment]
Sure Keith, done! Thanks!
