### ISSUE TITLE
Public cloud: Update contribution guidelines for each sub-project

### ISSUE THREAD

**Issue by k-dimple** [canonical/open-documentation-academy#41]
GitHub repo: https://github.com/canonical/ubuntu-cloud-docs

There are 7 sub-projects in this repo, each with their own 'Contribute to these docs' page. For instance, [this](https://canonical-aws.readthedocs-hosted.com/en/latest/aws-how-to/contribute-to-these-docs/) is the page for the AWS project.

We need to update these pages with - 
1. Guidelines stating all the places/files where updates are needed whenever a contributor adds a new page -  e.g. whenever a new how-to guide is written, links to it have to be included in multiple index files, along with appropriate changes in the relevant text.
2. Guidelines on creating a new category (if it does not already exist) - e.g. if a project does not have a 'reference' section, and the contributor wants to add content that classifies as reference material, what are the steps involved (files & folders to be created, files to be updated)

**Comment by activus-d** [comment]
@k-dimple I would like to work on this issue.

**Comment by k-dimple** [comment]
Sure @activus-d, thanks! I have assigned it to you.

**Comment by activus-d** [comment]
@k-dimple I've made a pull request to solve this issue and it's ready for your review.

**Comment by k-dimple** [comment]
@activus-d thanks for all the thought that you put into doing this well! Since it is now published, I am closing this PR.
