### ISSUE TITLE
LXD: Test the tutorial

### ISSUE THREAD

**Issue by ru-fu** [canonical/open-documentation-academy#43]
Documentation: https://documentation.ubuntu.com/lxd/en/latest/
GitHub repo: https://github.com/canonical/lxd
Contribution guide: https://documentation.ubuntu.com/lxd/en/latest/contributing/

---
The [First steps with LXD](https://documentation.ubuntu.com/lxd/en/latest/tutorial/first_steps/) tutorial guides the user through installation, initialisation, and the basic usage of LXD.

We'd like to user-test this tutorial to see how helpful it is, if anything is wrong or missing, and whether any parts of it need clarification. So the task is to follow the tutorial and note down any comments that could help to improve it. You can choose whether you prefer to provide the comments as feedback or do the changes yourself and open a PR to directly include the improvements you identified.

Requirements:
- You don't need prior knowledge of LXD, since the tutorial is aimed at new users.
- You need access to a Linux system for testing (WSL should also work).
- See [Diátaxis: Tutorials](https://diataxis.fr/tutorials/) for some background on tutorials.

**Comment by ru-fu** [comment]
Sounds great, thank you! I assigned the issue to you.

**Comment by pgfaller** [comment]
Pull request created: https://github.com/canonical/lxd/pull/13241

**Comment by pgfaller** [comment]
I've signed the CLA again; but I don't see a way for me to retry the workflow step.

**Comment by ru-fu** [comment]
Still failing after a rerun... not sure why, but I raised it. 
(Sorry for being slow responding, I'm off traveling at the moment.)

**Comment by pgfaller** [comment]
The pull request has been merged - can this issue be closed? (How?)

**Comment by ru-fu** [comment]
Thanks a lot @pgfaller !
