### ISSUE TITLE
Public Cloud: Write a how-to guide for AWS based on an existing tutorial

### ISSUE THREAD

**Issue by k-dimple** [canonical/open-documentation-academy#47]
GitHub repo: https://github.com/canonical/ubuntu-cloud-docs

Convert [this content](https://ubuntu.com/tutorials/upgrade-to-ubuntu-pro-at-scale-using-tokens-with-ssm#1-overview) written in the form of a tutorial to a how-to guide and include it under the AWS project [here](https://documentation.ubuntu.com/aws/en/latest/aws-how-to/instances/).

Refer to any of the other how-to guides in the same location to get an idea about the tone and format to be used. These [contribution guidelines](https://documentation.ubuntu.com/aws/en/latest/aws-how-to/contribute-to-these-docs/) could also help.

**Comment by k-dimple** [comment]
@krzysiekwie thanks for your interest in this one! First off calling the existing content a tutorial is not accurate, especially from a diataxis point of view. It includes steps to perform a task and is not really study-oriented. So the core content will form a nice how-to guide and which is why we want to include it in the how-to guides section of our technical documentation.

* I don't think we have a tutorial on writing how-to's but the ideas presented [here](https://diataxis.fr/how-to-guides/) can act a guideline. We are very much trying to follow the diataxis principles in Canonical.
* The task is about writing a how-to on the same topic. For getting a sense about the style to use you can refer to some of the [other how-to guides in the same project](https://documentation.ubuntu.com/aws/en/latest/aws-how-to/instances/). We try to give specific instructions and keep explanations and screenshots to a minimum. We assume that the reader is familiar with the environment that we are talking about and screenshots are only needed when something is obscure.

**Comment by krzysiekwie** [comment]
@k-dimple thanks for the clarification, I'll focus on the issue currently assigned to me for now, and possibly keep an eye on what happens in #48 before I come back to this one (that's if nobody picks it up by then :)

**Comment by billingsmoore** [comment]
I don't want to step on @krzysiekwie 's toes but #48 was more straightforward than I expected. So I'd be delighted to also take care of this one. I can have it done by April 15.

**Comment by krzysiekwie** [comment]
No worries - go ahead @billingsmoore

**Comment by k-dimple** [comment]
Thanks @krzysiekwie and @billingsmoore! I'll create a few more of these type of issues soon. So you can still choose to work on something similar.

**Comment by k-dimple** [comment]
Thanks @billingsmoore for getting this one done and for all the patience!
