### ISSUE TITLE
Public Cloud: Write a how-to guide for Azure based on an existing tutorial

### ISSUE THREAD

**Issue by k-dimple** [canonical/open-documentation-academy#48]
GitHub repo: https://github.com/canonical/ubuntu-cloud-docs

Convert [this content](https://ubuntu.com/tutorials/provision-an-ubuntu-virtual-machine-running-sql-server-in-azure#2-launch-an-ubuntu-vm-with-sql-server-installed) written in the form of a tutorial into a how-to guide and include it under the Azure project [here](https://documentation.ubuntu.com/azure/en/latest/azure-how-to/instances/).

Refer to any of the other how-to guides in the same location to get an idea about the tone and format to be used. These [contribution guidelines](https://documentation.ubuntu.com/azure/en/latest/azure-how-to/contribute-to-these-docs/) could also help.

**Comment by billingsmoore** [comment]
I'd like to adopt this task. I estimate a completion date of April 15.

**Comment by k-dimple** [comment]
Thanks @billingsmoore! I'll assign it to you, please feel to go ahead with it.

**Comment by billingsmoore** [comment]
Should I update the relevant index page to include the new how-to page?

**Comment by k-dimple** [comment]
Yes, that's a good point, you should. 

There are some contribution guidelines [here](https://documentation.ubuntu.com/azure/en/latest/azure-how-to/contribute-to-these-docs/) that you can refer to. Do let me know if they are useful or need some work or any other relevant feedback! (We recently updated them, so I would appreciate feedback from actual users :) )

**Comment by billingsmoore** [comment]
I was able to finish sooner than expected. I opened a pull request on the ubuntu-cloud-docs repo.

**Comment by k-dimple** [comment]
Yes, thanks! I'll hopefully take a look at it soon.

**Comment by k-dimple** [comment]
This issue was handled together with #47.
