### ISSUE TITLE
Landscape: Update term "Repositories"

### ISSUE THREAD

**Issue by YanisaHS** [canonical/open-documentation-academy#50]
Enhance the [existing description of **repositories**](https://ubuntu.com/landscape/docs/explanation-repositories), and add more information on how it relates to Landscape. Your entry shouldn’t simply describe what a repository is; the goal is to explain how repositories *relate to Landscape*. You should explicitly relate it to [repository mirroring](https://ubuntu.com/landscape/docs/explanation-about-repository-mirroring).

You should provide the entry as a Markdown file and put it in this file path: `landscape/explanation/glossary/repositories.md`. If any directories are missing, add them so your file path matches the one provided.

**Prerequisites**

A general understanding of how Landscape works and experience using and installing Landscape. 

However, you don’t need any prior experience if you’re willing to explore the [Landscape Docs](https://ubuntu.com/landscape/docs) and spend time learning about Landscape.

See also: [Contribute to our documentation](https://ubuntu.com/landscape/docs/contribute-to-the-landscape-documentation).

_Note: Before working on this issue, please comment and ask to be assigned to it. This is to ensure multiple people aren't working on the same issue._

**Comment by YanisaHS** [comment]
@TropicolX Absolutely! Let me know if you have any questions :)

**Comment by TropicolX** [comment]
Hi @YanisaHS , I've created a PR for this issue. Looking forward to your feedback and guidance!
