### ISSUE TITLE
Public Cloud: Change table format

### ISSUE THREAD

**Issue by k-dimple** [canonical/open-documentation-academy#51]
GitHub repo: https://github.com/canonical/ubuntu-cloud-docs

The tables on [this](https://documentation.ubuntu.com/azure/en/latest/azure-how-to/instances/find-ubuntu-images/) page consists of two columns each ('Kind', URN'). Convert them into 3 columns each with titles: 'Architecture', 'Hyper-V Generation' and 'URN'.

**Comment by krzysiekwie** [comment]
Happy to try this as my first issue here, I can get this done within a day from assignment

**Comment by k-dimple** [comment]
Hello @krzysiekwie! Thanks, please go ahead and try it. I've assigned it to you.

**Comment by krzysiekwie** [comment]
Hi @k-dimple I added the basic edit in https://github.com/canonical/ubuntu-cloud-docs/pull/206 
(don't think I can use fixes #51 directly on ubuntu-cloud-docs).

Also I'm not sure if the first two columns should get cenetered. Github and my local rst preview does not render centering. I tried the three formats from:
https://github.com/krzysiekwie/ubuntu-cloud-docs/blob/change-formatting/doc-cheat-sheet-myst.md 
in
https://github.com/krzysiekwie/ubuntu-cloud-docs/blob/change-formatting/azure/azure-how-to/instances/find-ubuntu-images.rst

Let me know what you think.

**Comment by k-dimple** [comment]
Hi @krzysiekwie, adding the edit directly in the repo is perfectly fine. I have put in a comment there. 

Regarding the centring, I don't think we need to centre the first two columns. It looks better left-aligned. 
Using ":align: center" works for the whole table. Currently, I don't think there's an option to centre only certain columns using list-tables.
