### ISSUE TITLE
Netplan: Add info on building docs to README

### ISSUE THREAD

**Issue by rkratky** [canonical/open-documentation-academy#52]
## Context

The [Netplan project](https://github.com/canonical/netplan) docs are hosted within the same repo as the code, but the main repo README (or the CONTRIBUTING file) has no information on how to contribute to the docs. This an oversight, albeit one that should be simple to fix.

## Task

The README should contain basic info on:

- docs location (the `doc/` subdirectory)
- docs format (Sphinx/rST)
- repo setup (Docs Starter Pack: https://github.com/canonical/sphinx-docs-starter-pack)
- hosting (ReadTheDocs: https://netplan.readthedocs.io/)
- local building/testing of the docs

Inspiration: https://github.com/canonical/ubuntu-packaging-guide

**Comment by ade555** [comment]
Hi, @rkratky please assign this issue to me. I should be done with it by COB tomorrow.

**Comment by rkratky** [comment]
Thank you, @ade555. Closing this issue as completed.
