### ISSUE TITLE
Multipass: improve language in the Tutorials

### ISSUE THREAD

**Issue by rkratky** [canonical/open-documentation-academy#55]
## Context

[Multipass tutorials](https://multipass.run/docs/tutorials) are in a reasonably good shape, but there are (as always) little things that could be improved to offer better user experience. One of them is the use of language that's largely superfluous and doesn't help the user.

The Multipass docs are maintained in and published from the Ubuntu Discourse forum. To suggest changes in a Discourse-hosted docs page, scroll all the way down to the bottom of the page and open the page to which the "Help improve this document in the forum" link points. On the Discourse page, scroll to the bottom of the article (if there are comments, then the bottom of the article is just where the comments start, i.e. not at the very bottom of the page) and click "Edit". (You need an account on Ubuntu Discourse.)

## Task

Modify the language throughout the docs set to not use unnecessary verbiage, including:

- "simply"
- "please"
- sentences starting with "You can" (where appropriate)
- future tense (where not appropriate, which is almost everywhere)
- ...

You can find more examples and guidance in the [Canonical Documentation Style Guide](https://docs.ubuntu.com/styleguide/en/).

**Comment by rkratky** [comment]
Hi @geoffreynyaga. Thanks for your interest in this issue. The absence of the "Edit" button is caused by a Discourse setting that prevents anyone who has not done a certain amount of reading & commenting from modifying existing topics. It's a bit unfortunate, but that's the way it works.

What we've been doing with docs that are hosted in Discourse, is we'd take the Markdown sources, copy them over top this repo, and let contributors work on the files here until the content is ready. Then someone submits them back to Discourse.

What I didn't realize is that this particular issue makes this approach a bit complicated because the modifications would likely be occurring in many different places in the docs set -- so, copying _everything_ to this repo would be cumbersome (especially considering that there might only be one or two small changes in each file).

We need to come up with a better way of handling changes to Discourse docs.

**Comment by rkratky** [comment]
Hi @geoffreynyaga. Just wanted to let you know I've trying to come up with a sane way of dealing with the mechanics of how to allow you to work on this issue, but I don't have any satisfactory answers yet. I really should've considered this problem before defining this issue for the Academy :/

**Comment by giuliazanchi** [comment]
Hi @PitifulPete, thank you for your suggestion, breaking it down is actually a very good idea. I have reframed this issue to specifically target Multipass tutorials, let us know if that's something you'd like to contribute to! 

I will look at Multipass docs closely and try to identify other areas of improvement. In the meantime, please let us know if you have something else in mind, such as application of the [Canonical Documentation Style Guide](https://docs.ubuntu.com/styleguide/en/), examples and instructions provided in the docs, etc.

**Comment by PitifulPete** [comment]
Hi @giuliazanchi. Yes, I'd like to contribute. Thank you!

**Comment by giuliazanchi** [comment]
> PitifulPete

Great! You can start by assigning this issue to yourself. Then, please check that you have permission to edit the relevant Discourse pages. To do so, go to [](https://multipass.run/docs/tutorials), select a tutorial and click "Help improve this document in the forum" at the bottom of the page. 

If you don't have the required permissions on Discourse, let me know and I'll set up a temporary copy that you can work on here on GitHub.

Thanks again for your help,
Giulia

**Comment by PitifulPete** [comment]
@giuliazanchi, i still can't edit on the forum so i will need a temporary file

**Comment by giuliazanchi** [comment]
@PitifulPete I added three Markdown files to the Multipass folder, using short filenames for simplicity (Linux, macOS, Windows). Let me know if you need help!

**Comment by giuliazanchi** [comment]
Hi @PitifulPete , please refresh your copy of the Linux tutorial, I added in some punctuation fixes (see PR #83) that were suggested by another contributor. Thanks!

**Comment by PitifulPete** [comment]
Hi @giuliazanchi, peep [this](https://github.com/canonical/open-documentation-academy/pull/90)

**Comment by giuliazanchi** [comment]
Hi @PitifulPete , I'll look at it properly tomorrow and let you know if you're on the right track, thanks so much for such a speedy contribution!

**Comment by giuliazanchi** [comment]
Done! Thanks again @PitifulPete
