### ISSUE TITLE
Installing WSL for windows keeps returning "The operation timed out"

### ISSUE THREAD

**Issue by ade555** [canonical/open-documentation-academy#57]
The `wsl --install`  command keeps returning "The operation timed out" after 4-5 minutes even when I type it in administrator mode.

**Comment by YanisaHS** [comment]
Hi @ade555 - I'm going to close this issue because it isn't related to Canonical's Open Documentation Academy project.

Here's a link to Microsoft's WSL Documentation: https://learn.microsoft.com/en-us/windows/wsl/

Good luck with your issue!

**Comment by ade555** [comment]
Thank you @YanisaHS. I made a PR for this issue since it took me almost an entire day to figure it out. I wouldn't want others to go through the same.
