### ISSUE TITLE
Anbox Cloud: Usability testing for the appliance tutorial

### ISSUE THREAD

**Issue by keirthana** [canonical/open-documentation-academy#75]
Disclaimer: Anbox Cloud requires Ubuntu Pro and while the documentation source is open, the product source is not.

Licensing:
- For contributions to the documentation, you will be required to sign the [CLA](https://ubuntu.com/legal/contributors).
- The Anbox Cloud documentation is licensed under the Creative Commons Attribution-Share Alike 3.0 Unported License. 

The [Anbox Cloud tutorial on installing the appliance](https://anbox-cloud.io/docs/tutorial/installing-appliance) needs to be tested for gaps in understanding by someone who is new to the product.

Basic:
Run through the steps in the tutorial and perform the steps as you go and share feedback on where you get stuck because of missing or incorrect information, where you would like more information to enhance your learning process. 

Advanced (Optional):
If you are confident about the changes you want in the tutorial, raise a pull request against the [Anbox Cloud documentation repository](https://github.com/canonical/anbox-cloud-docs). Please note that the Anbox Cloud documentation follows the [DÃ­ataxis](https://diataxis.fr/) approach. See https://diataxis.fr/tutorials/ for information on how to apply Diataxis for a tutorial.

**Comment by gerryRcom** [comment]
Hi keirthana, I'd be happy to run through the install tutorial and see if there are gaps, I'm not familiar with the product but am familiar with software installations on servers so should be able to get through it.

**Comment by keirthana** [comment]
Hi @gerryRcom, thanks for picking this up. Actually unfamiliarity with the product will help in this exercise because the that's the point of the tutorial - to teach new users. 

Let me know if you have any questions.

**Comment by gerryRcom** [comment]
Hi, with the exception of one missing `sudo` command the playbook worked out fine, spun up a local sever with service installed without issue. I submitted a [pull request](https://github.com/canonical/anbox-cloud-docs/pull/87) to add it, also updated the status command output while I was at it as the current version is a bit newer that the one that was there.

**Comment by keirthana** [comment]
Thank you very much for your time on this @gerryRcom. I have emailed you about the CLA check failing. I will keep you posted.

**Comment by keirthana** [comment]
Hi @gerryRcom,

The updates are now live at [https://anbox-cloud.io/docs/tutorial/installing-appliance](https://anbox-cloud.io/docs/tutorial/installing-appliance). Thank you very much.
