### ISSUE TITLE
Launchpad: create subsections in left-hand side navigation menu for the `how-to` section

### ISSUE THREAD

**Issue by jugmac00** [canonical/open-documentation-academy#76]
Documentation: https://documentation.ubuntu.com/launchpad/en/latest/how-to/
GitHub repo: https://github.com/canonical/launchpad-manual
Contribution guide: https://documentation.ubuntu.com/launchpad/en/latest/contribute-to-our-docs/

The how-to section has been re-organized into coherent sections, but the navigation menu on the left does not reflect these changes and is very hard to read.

Task: apply the same subsections to the navigation menu

We use sphinx and the rst format to build our documentation.

**Comment by nbarbarick** [comment]
Hi, I would like to tackle this issue, and could likely finish within a week. 

Can I be assigned it, please?

**Comment by jugmac00** [comment]
I do not have permissions to assign you the issue, but I am sure @degville will do soon. IMHO you can start working on it.

Thanks a lot for your support!

**Comment by jugmac00** [comment]
@nbarbarick Thanks again for working on this! Your contributions are highly appreciated!

The new, beautiful how-to navigation can he seen on https://documentation.ubuntu.com/launchpad/en/latest/how-to/
