### ISSUE TITLE
Launchpad: fix spelling issues

### ISSUE THREAD

**Issue by jugmac00** [canonical/open-documentation-academy#77]
Documentation: https://documentation.ubuntu.com/launchpad/en/latest/how-to/
GitHub repo: https://github.com/canonical/launchpad-manual
Contribution guide: https://documentation.ubuntu.com/launchpad/en/latest/contribute-to-our-docs/

For the migration of the documentation, a lot of existing documentation was transferred from other platforms, where no checks were performed before. Some of the added pages were excluded from the new spellchecks.

Task: remove the exceptions one by one from https://github.com/canonical/launchpad-manual/blob/main/.sphinx/spellingcheck.yaml (e.g. `|!_build/explanation/javascript-integration-testing/index.html`), run the spell checks (`make spelling`), fix the spelling errors and/or include new words to https://github.com/canonical/launchpad-manual/blob/main/.custom_wordlist.txt, and create a pull request, preferably one for each page to make reviews easier. We use British English at Canonical.

**Comment by gerryRcom** [comment]
Hi jugmac00, I can give this a go if no one is currently working on it?

**Comment by jugmac00** [comment]
@gerryRcom That would be fantastic 😊

**Comment by gerryRcom** [comment]
Great, I'll get the first change in shortly to make sure I'm on the right track. I'm not sure if I picked a bad [first page](https://documentation.ubuntu.com/launchpad/en/latest/explanation/hacking/) but there seems to be a lot of "new" words to add to the custom word file.

**Comment by jugmac00** [comment]
It is entirely possible that a lot of new words need to be added, but it should get better with every new article. Also, it is definitely possible that there are some typos.

Thanks for looking into this. Highly appreciated 👍

**Comment by sfadriaan** [comment]
@jugmac00 Created a [pull request](https://github.com/canonical/launchpad-manual/pull/81) for the "Integration Testing in JavaScript" page. Thanks for the opportunity

**Comment by sfadriaan** [comment]
@jugmac00 it seems like @gerryRcom and I have resolved all the pages from the exclusion list. I assume this issue can be closed? Thanks for the opportunity to contribute 👍

**Comment by jugmac00** [comment]
@sfadriaan Indeed, you are right. Thanks so much for both your and @gerryRcom's support!

We, the Launchpad team, and also the technical authors here at Canonical are still blown away from all the community contributions we received! :tada:

**Comment by sfadriaan** [comment]
@jugmac00 thanks for the opportunity! I learnt a lot
