### ISSUE TITLE
Ubuntu WSL: update and improve Install Ubuntu on WSL2 guide

### ISSUE THREAD

**Issue by edibotopic** [canonical/open-documentation-academy#85]
Update the following guide:

[Install Ubuntu on WSL2](https://canonical-ubuntu-wsl.readthedocs-hosted.com/en/latest/guides/install-ubuntu-wsl2/)

# Background

This Ubuntu WSL guide explains multiple ways to install Ubuntu WSL on a Windows device.

There are some quick improvements that can be made to the guide:

- The latest Ubuntu LTS (24.04) should be referenced instead of any older versions where possible.
- The tutorial is about installing Ubuntu on WSL, not only installing WSL, and this should be more clearly stated in **What You Will Learn**.
- There is a reference to running "a graphical application" at the end of the tutorial but it is not clear what application (if any) is being referred to. This reference should be clarified or removed.
- Syntax highlighting for CLI commands might not correspond to the user's CLI experience and should be removed by labelling markdown code blocks as **text** (rather than powershell or bash).

You are welcome to highlight any other small issues that you observe and suggest changes.

# Prerequisites

Access to a Windows machine and a familiarity with WSL would be helpful for understanding the content and testing any commands.

The specific issues outlined above can be addressed without significant experience of WSL or access to a Windows machine.

**Comment by krzysiekwie** [comment]
Happy to do it this week/weekend (actually need to switch to WSL instead of dual-booting :)

**Comment by krzysiekwie** [comment]
@edibotopic The [PR](https://github.com/canonical/open-documentation-academy/pull/98) is a minimal edit to address your issue description. Feels like maybe the text was first planned to be a more complete/ less formal tutorial but got quickly published as a guide. Let me know if you think it should get expanded/revised further.

**Comment by edibotopic** [comment]
That's great @krzysiekwie . I appreciate the quick work on this. I think you might be right about the confusion between tutorial and guide also. I will have a look at what you submitted ASAP and get back to you with any comments. Thanks again!
